version: '3'

networks:
  mongodbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.1.0/28

# volumes:
#   data-server-1-volume:
#   data-server-2-volume:
#   data-server-3-volume:

services:
  router:
    image: router/mongo:4.2.1
    container_name: router
    hostname: router
    command: mongos --configdb rs-config-server/config1:27019,config2:27019 --bind_ip_all
    ports:
      - 27017:27017
    networks:
      mongodbnet:
        ipv4_address: 172.1.1.2
  
  config-server-1:
    image: config-server-1/mongo:4.2.1
    container_name: config-server-1
    hostname: config-server-1
    command: mongod --configsvr --replSet rs-config-server
    networks:
      mongodbnet:
        ipv4_address: 172.1.1.3
  
  config-server-2:
    image: config-server-1/mongo:4.2.1
    container_name: config-server-2
    hostname: config-server-2
    command: mongod --configsvr --replSet rs-config-server
    networks:
      mongodbnet:
        ipv4_address: 172.1.1.4

  data-server-1:
    image: data-server-1/mongo:4.2.1
    container_name: data-server-1
    hostname: data-server-1
    command: mongod --shardsvr --replSet rs1
    networks:
      mongodbnet:
        ipv4_address: 172.1.1.5

  data-server-2:
    image: data-server-2/mongo:4.2.1
    container_name: data-server-2
    hostname: data-server-2
    command: mongod --shardsvr --replSet rs2
    networks:
      mongodbnet:
        ipv4_address: 172.1.1.5

  data-server-3:
    image: data-server-3/mongo:4.2.1
    container_name: data-server-3
    hostname: data-server-3
    command: mongod --shardsvr --replSet rs3
    networks:
      mongodbnet:
        ipv4_address: 172.1.1.5